### PR TITLE
exclude clojure any?

### PR DESCRIPTION
**Pull request by jiyouyou125**
fix any? warning

### CODE REVIEW

**Review by philomates — APPROVED** [review]
Cool, thanks for taking the time to fix this!

**Comment by philomates** [comment]
oops, turns out I don't have permissions to merge or deploy things on `lein-midje` (which I thought I had).

@marick would you be able to either grant me permissions to contribute to this repo and deploy things to this project on clojars, or run a merge/deploy yourself? Thanks!

**Comment by marick** [comment]
Added you and did the merge.

**Comment by philomates** [comment]
Thanks @marick! Could you also add me as a collaborator on the clojars project so I can deploy the changes?

**Comment by marick** [comment]
I tried, but I got this:

     Blistering barnacles! Something's not shipshape:
        No such user: philomates

**Comment by philomates** [comment]
@marick on clojars I'm [`phillipmates`](https://clojars.org/users/phillipmates); sorry for not mentioning earlier

**Comment by marick** [comment]
Should be done.

**Comment by philomates** [comment]
thanks! 
@jiyouyou125 I've deployed this change as `lein-midje` `3.2.2.`

**Comment by logaan** [comment]
Worth updating your readme etc to refer to 3.2.2.

**Pull request merged**
